---
title: "Statistiky"
format: html
---

Následující statistiky uvádějí pravděpodobnost charakteristik dalšího náhradníka dané volební strany. Pro každý kraj se bere aktuální první náhradník, přičemž se počítá za každého poslance na příslušné kandidátce (tzn. pro kolik poslanců je náhradníkem).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, warning=FALSE, message=FALSE)
xfun::pkg_attach("dplyr", "gt")
```

### Podle pohlaví

```{r sex}
nahradnici <- readRDS(here::here("psp/data/candidates.rds")) |>
  select(JMENO, PRIJMENI, VOLKRAJ, NAZVOLKRAJ, KSTRANA, NAZ_STR, PSTRANA, NSTRANA, state, weight) |> 
  filter(state == 21)

parties <- readRDS(here::here("psp/data/parties.rds"))

pohlavi <- function (surname) {
  if (grepl("(ová|á$)", surname)) { # primitivní heuristika
    return("Ž")
  } else {
    return("M")
  }  
}

pctg <- scales::label_percent(
  suffix = " %"
)

nahradnici %>%
  mutate(
    pohlavi = pohlavi(PRIJMENI)
  ) %>%
  group_by(NAZ_STR) %>%
  summarise(
    total_weight = sum(weight),
    Žena = pctg(sum(weight[pohlavi == "Ž"]) / total_weight),
    Muž  = pctg(sum(weight[pohlavi == "M"]) / total_weight),
    .groups = "drop"
  ) %>%
  select(-total_weight) %>%
  gt()

```

### Podle navrhující strany (SPOLU)
```{r spolu}
nahradnici %>%
  filter(KSTRANA == 11) %>%
  ungroup() %>%
  group_by(NSTRANA) %>%
  summarise(total_weight = sum(weight), .groups = "drop_last") %>%
  mutate(pct = pctg(total_weight / sum(total_weight))) %>%
  left_join(parties, by = join_by(NSTRANA == PSTRANA)) %>%
  select(ZKRATKAP8, pct) %>%
  gt()
```

### Podle politické příslušnosti (SPD)
```{r spd}
nahradnici %>%
  filter(KSTRANA == 6) %>%
  ungroup() %>%
  group_by(PSTRANA) %>%
  summarise(total_weight = sum(weight), .groups = "drop_last") %>%
  mutate(pct = pctg(total_weight / sum(total_weight))) %>%
  left_join(parties, by = "PSTRANA") %>%
  select(ZKRATKAP8, pct) %>%
  gt()
```